# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.0.11:3306/property_manage?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password:

# 日志
logging:
  path: /data/project/property-manage/code

server:
  port: 8082